const swaggeAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json';
const endpointsFiles = ['./src/routes/index.js'];

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3333",
    schemes: ["http"],
    securityDefinitions: {
        apiKeyAuth: {
        type: "apiKey",
        in: "header", // can be 'header', 'query' or 'cookie'
        name: "Authentication", // name of the header, query parameter or cookie
        description: "Insira a chave de atentiação JWT",
        },
    },
};


swaggeAutogen(outputFile, endpointsFiles,doc).then(() => {
    require('./src/server')
});